apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-api
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels: { app: iot-api }
  template:
    metadata:
      labels: { app: iot-api }
    spec:
      containers:
      - name: api
        image: iot-api:1               
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/"
        readinessProbe:
          httpGet: { path: "/", port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: "/", port: 5000 }
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: iot-api
  namespace: iot
spec:
  selector: { app: iot-api }
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
